---
engine_version: 0.4.27
file_version: 2024-07-29 10:00:44.395346000 Z
resources:
- name: home
  preferences: {}
  updated_at: 2024-07-29 10:00:44.395346000 +00:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2024-07-29 10:00:03.192024000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description: 
  updated_at: 2024-07-29 10:00:03.244558000 +00:00
